/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mainapp;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author lalo_
 */
public class LogInMenu extends javax.swing.JFrame {

    //public DefaultTableModel modelAcc = (DefaultTableModel) this.jTable_Accounts.getModel();
    /**
     * Creates new form LogInMenu
     */
    
    SignInMenu Sim = new SignInMenu();
    SenderMenu Sen = new SenderMenu();
    //DefaultTableModel Tm = new DefaultTableModel();
    public static String EmailLogged = "";
    public static String PasswordLogged = "";
    public LogInMenu() {        
        initComponents();
        Emails.addFontStyle(this.jTextF_Email);
        Emails.addFontStyle(this.jPasswordF_Password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Accounts = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextF_Email = new javax.swing.JTextField();
        jPasswordF_Password = new javax.swing.JPasswordField();
        jButton_LogIn = new javax.swing.JButton();
        jButton_Close = new javax.swing.JButton();
        jButton_SignIn = new javax.swing.JButton();
        jCheckB_SeePassword = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jTable_Accounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"rober", "12"},
                {"tadprgs@gmail.com", "jerbeftltmvxfqam"}
            },
            new String [] {
                "Email", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable_Accounts);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 2, true));

        jTextF_Email.setBackground(new java.awt.Color(204, 204, 204));
        jTextF_Email.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextF_Email.setText("Write the Email here:");
        jTextF_Email.setToolTipText("Write Email.");
        jTextF_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 0)));
        jTextF_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextF_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextF_EmailFocusLost(evt);
            }
        });
        jTextF_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextF_EmailKeyPressed(evt);
            }
        });

        jPasswordF_Password.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordF_Password.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPasswordF_Password.setText("Write the Password here:");
        jPasswordF_Password.setToolTipText("Write Password");
        jPasswordF_Password.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 0)));
        jPasswordF_Password.setEchoChar('\u0000');
        jPasswordF_Password.setOpaque(true);
        jPasswordF_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordF_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordF_PasswordFocusLost(evt);
            }
        });
        jPasswordF_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordF_PasswordKeyPressed(evt);
            }
        });

        jButton_LogIn.setBackground(new java.awt.Color(0, 0, 255));
        jButton_LogIn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton_LogIn.setText("Log In");
        jButton_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogInActionPerformed(evt);
            }
        });

        jButton_Close.setBackground(new java.awt.Color(0, 0, 204));
        jButton_Close.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton_Close.setText("Close");
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });

        jButton_SignIn.setBackground(new java.awt.Color(0, 0, 255));
        jButton_SignIn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton_SignIn.setText("Sign In");
        jButton_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SignInActionPerformed(evt);
            }
        });

        jCheckB_SeePassword.setText("See Password");
        jCheckB_SeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckB_SeePasswordActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mainapp/Logo-email.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_SignIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Close))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPasswordF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckB_SeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton_LogIn))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckB_SeePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_LogIn)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Close)
                    .addComponent(jButton_SignIn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogInActionPerformed
        // TODO add your handling code here:
        
        String Email = this.jTextF_Email.getText();
        String PassW = this.jPasswordF_Password.getText();
        boolean Acces = false, EmailE = false;
        
        for(int i = 0; i < this.jTable_Accounts.getRowCount();i++)
        {
            if(this.jTable_Accounts.getValueAt(i, 0).equals(Email))
            {
                if(this.jTable_Accounts.getValueAt(i, 1).equals(PassW))
                {
                    Acces = true;
                    EmailE = true;
                    break;
                }
                JOptionPane.showMessageDialog(null, "The Password does not match!");
                EmailE =  true;
            }   
        }
        if(!EmailE)
        {
            JOptionPane.showMessageDialog(null, "The Email does not exist!");
        }
        if(Acces)
        {
            EmailLogged = Email; 
            PasswordLogged = PassW;
            this.jTextF_Email.setText("");
            this.jPasswordF_Password.setText("");
            JOptionPane.showMessageDialog(null,"Welcome!");
            Sen.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton_LogInActionPerformed

    private void jButton_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SignInActionPerformed
        // TODO add your handling code here:
        Sim.setVisible(true);
    }//GEN-LAST:event_jButton_SignInActionPerformed

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_CloseActionPerformed

    private void jCheckB_SeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckB_SeePasswordActionPerformed
        // TODO add your handling code here:
        if(this.jCheckB_SeePassword.isSelected())
        {
            this.jPasswordF_Password.setEchoChar('\u0000');
        }else if(!this.jCheckB_SeePassword.isSelected())
        {
            this.jPasswordF_Password.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jCheckB_SeePasswordActionPerformed

    private void jTextF_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextF_EmailFocusGained
        // TODO add your handling code here:
        if(this.jTextF_Email.getText().equals("Write the Email here:"))
        {
            this.jTextF_Email.setText(null);
            this.jTextF_Email.requestFocus();
            Emails.removeFontStyle(jTextF_Email);
        }
    }//GEN-LAST:event_jTextF_EmailFocusGained

    private void jTextF_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextF_EmailFocusLost
        // TODO add your handling code here:
        if(this.jTextF_Email.getText().length() == 0)
        {
            Emails.addFontStyle(jTextF_Email);
            this.jTextF_Email.setText("Write the Email here:");
        }
    }//GEN-LAST:event_jTextF_EmailFocusLost

    private void jPasswordF_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordF_PasswordFocusGained
        // TODO add your handling code here:
        if(this.jPasswordF_Password.getText().equals("Write the Password here:"))
        {
            this.jPasswordF_Password.setText(null);
            this.jPasswordF_Password.requestFocus();
            this.jPasswordF_Password.setEchoChar('*');
            Emails.removeFontStyle(this.jPasswordF_Password);
        }
    }//GEN-LAST:event_jPasswordF_PasswordFocusGained

    private void jPasswordF_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordF_PasswordFocusLost
        // TODO add your handling code here:
        if(this.jPasswordF_Password.getText().length() == 0)
        {
            Emails.addFontStyle(this.jPasswordF_Password);
            this.jPasswordF_Password.setText("Write the Password here:");
        }
    }//GEN-LAST:event_jPasswordF_PasswordFocusLost

    private void jTextF_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextF_EmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            this.jPasswordF_Password.requestFocus();
        }
    }//GEN-LAST:event_jTextF_EmailKeyPressed

    private void jPasswordF_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordF_PasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String Email = this.jTextF_Email.getText();
        String PassW = this.jPasswordF_Password.getText();
        boolean Acces = false, EmailE = false;
        
        for(int i = 0; i < this.jTable_Accounts.getRowCount();i++)
        {
            if(this.jTable_Accounts.getValueAt(i, 0).equals(Email))
            {
                if(this.jTable_Accounts.getValueAt(i, 1).equals(PassW))
                {
                    Acces = true;
                    EmailE = true;
                    break;
                }
                JOptionPane.showMessageDialog(null, "The Password does not match!");
                EmailE =  true;
            }   
        }
        if(!EmailE)
        {
            JOptionPane.showMessageDialog(null, "The Email does not exist!");
        }
        if(Acces)
        {
            EmailLogged = Email; 
            PasswordLogged = PassW;
            this.jTextF_Email.setText("");
            this.jPasswordF_Password.setText("");
            JOptionPane.showMessageDialog(null,"Welcome!");
            Sen.setVisible(true);
            dispose();
        }
        }
    }//GEN-LAST:event_jPasswordF_PasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_LogIn;
    private javax.swing.JButton jButton_SignIn;
    private javax.swing.JCheckBox jCheckB_SeePassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordF_Password;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_Accounts;
    private javax.swing.JTextField jTextF_Email;
    // End of variables declaration//GEN-END:variables
}
