/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mainapp;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lalo_
 */
public class SignInMenu extends javax.swing.JFrame {

    
    /**
     * Creates new form SignInMenu
     */
    public SignInMenu() {
        initComponents();
        Emails.addFontStyle(jTextField_Email);
        Emails.addFontStyle(this.jPasswordField_ConfirmPassword);
        Emails.addFontStyle(this.jPasswordField_Password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_Email = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jPasswordField_ConfirmPassword = new javax.swing.JPasswordField();
        jButton_SigIn = new javax.swing.JButton();
        jCheckBox_SeePassword = new javax.swing.JCheckBox();
        jButton_GoBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102), 2));

        jTextField_Email.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Email.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextField_Email.setText("Add Email here:");
        jTextField_Email.setToolTipText("Write Email.");
        jTextField_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 51)));
        jTextField_Email.setOpaque(true);
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyPressed(evt);
            }
        });

        jPasswordField_Password.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_Password.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPasswordField_Password.setText("Write the Password here:");
        jPasswordField_Password.setToolTipText("Write Password");
        jPasswordField_Password.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 0)));
        jPasswordField_Password.setEchoChar('\u0000');
        jPasswordField_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusLost(evt);
            }
        });
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyPressed(evt);
            }
        });

        jPasswordField_ConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_ConfirmPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jPasswordField_ConfirmPassword.setText("Confirm the Password here:");
        jPasswordField_ConfirmPassword.setToolTipText("Confirm Password");
        jPasswordField_ConfirmPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 255, 0)));
        jPasswordField_ConfirmPassword.setEchoChar('\u0000');
        jPasswordField_ConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_ConfirmPasswordFocusLost(evt);
            }
        });
        jPasswordField_ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_ConfirmPasswordActionPerformed(evt);
            }
        });
        jPasswordField_ConfirmPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_ConfirmPasswordKeyPressed(evt);
            }
        });

        jButton_SigIn.setBackground(new java.awt.Color(0, 0, 204));
        jButton_SigIn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton_SigIn.setText("Sign In");
        jButton_SigIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SigInActionPerformed(evt);
            }
        });

        jCheckBox_SeePassword.setText("See Password");
        jCheckBox_SeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_SeePasswordActionPerformed(evt);
            }
        });

        jButton_GoBack.setBackground(new java.awt.Color(0, 0, 204));
        jButton_GoBack.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton_GoBack.setText("Go Back");
        jButton_GoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GoBackActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mainapp/5087579.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Email)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_SigIn)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox_SeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPasswordField_Password)
                            .addComponent(jPasswordField_ConfirmPassword))
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_GoBack)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox_SeePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_GoBack)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_SigIn)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SigInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SigInActionPerformed
        // TODO add your handling code here:
        String Email = this.jTextField_Email.getText();
        String PassW = "";
        boolean Confirm = false;
        if(this.jTextField_Email.getText().equals("Add Email here:"))
        {
            JOptionPane.showMessageDialog(null, "Write the Email!");
        }else
        {
            if(this.jPasswordField_ConfirmPassword.getText().equals(this.jPasswordField_Password.getText()))
            {
            PassW = this.jPasswordField_Password.getText();
            Confirm = true;
            }else
            {
            JOptionPane.showMessageDialog(null, "The Passwords are no the same!");
            }
        }
        if(Confirm)
        {
            LogInMenu Lim = new LogInMenu();
            DefaultTableModel modelAcc2 = (DefaultTableModel) Lim.jTable_Accounts.getModel();
            //Agregar renglon en la tabla:
            modelAcc2.addRow(new Object[]{Email,PassW});
            JOptionPane.showMessageDialog(null, "Email registered succesfully!");
        }
    }//GEN-LAST:event_jButton_SigInActionPerformed

    private void jButton_GoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GoBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_GoBackActionPerformed

    private void jCheckBox_SeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_SeePasswordActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBox_SeePassword.isSelected())
        {
            this.jPasswordField_ConfirmPassword.setEchoChar('\u0000');
            this.jPasswordField_Password.setEchoChar('\u0000');
        }else if(!this.jCheckBox_SeePassword.isSelected())
        {
            this.jPasswordField_ConfirmPassword.setEchoChar('\u2022');
            this.jPasswordField_Password.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jCheckBox_SeePasswordActionPerformed

    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusGained
        // TODO add your handling code here:
        if(this.jTextField_Email.getText().equals("Add Email here:"))
        {
            this.jTextField_Email.setText(null);
            this.jTextField_Email.requestFocus();
            Emails.removeFontStyle(jTextField_Email);
        }
    }//GEN-LAST:event_jTextField_EmailFocusGained

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
        // TODO add your handling code here:
        if(this.jTextField_Email.getText().length() == 0)
        {
            Emails.addFontStyle(jTextField_Email);
            this.jTextField_Email.setText("Add Email here:");
        }
    }//GEN-LAST:event_jTextField_EmailFocusLost

    private void jPasswordField_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusGained
        // TODO add your handling code here:
        if(this.jPasswordField_Password.getText().equals("Write the Password here:"))
        {
            this.jPasswordField_Password.setText(null);
            this.jPasswordField_Password.requestFocus();
            this.jPasswordField_Password.setEchoChar('*');
            Emails.removeFontStyle(this.jPasswordField_Password);
        }
    }//GEN-LAST:event_jPasswordField_PasswordFocusGained

    private void jPasswordField_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusLost
        // TODO add your handling code here:
        if(this.jPasswordField_Password.getText().length() == 0)
        {
            Emails.addFontStyle(this.jPasswordField_Password);
            this.jPasswordField_Password.setText("Write the Password here:");
        }
    }//GEN-LAST:event_jPasswordField_PasswordFocusLost

    private void jPasswordField_ConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordFocusGained
        // TODO add your handling code here:
        if(this.jPasswordField_ConfirmPassword.getText().equals("Confirm the Password here:"))
        {
            this.jPasswordField_ConfirmPassword.setText(null);
            this.jPasswordField_ConfirmPassword.requestFocus();
            this.jPasswordField_ConfirmPassword.setEchoChar('*');
            Emails.removeFontStyle(this.jPasswordField_ConfirmPassword);
        }
    }//GEN-LAST:event_jPasswordField_ConfirmPasswordFocusGained

    private void jPasswordField_ConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordFocusLost
        // TODO add your handling code here:
        if(this.jPasswordField_ConfirmPassword.getText().length() == 0)
        {
            Emails.addFontStyle(this.jPasswordField_ConfirmPassword);
            this.jPasswordField_ConfirmPassword.setText("Confirm the Password here:");
        }
    }//GEN-LAST:event_jPasswordField_ConfirmPasswordFocusLost

    private void jTextField_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            this.jPasswordField_Password.requestFocus();
        }
    }//GEN-LAST:event_jTextField_EmailKeyPressed

    private void jPasswordField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            this.jPasswordField_ConfirmPassword.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField_PasswordKeyPressed

    private void jPasswordField_ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_ConfirmPasswordActionPerformed

    private void jPasswordField_ConfirmPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_ConfirmPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
        String Email = this.jTextField_Email.getText();
        String PassW = "";
        boolean Confirm = false;
        if(this.jTextField_Email.getText().equals("Add Email here:"))
        {
            JOptionPane.showMessageDialog(null, "Write the Email!");
        }else
        {
            if(this.jPasswordField_ConfirmPassword.getText().equals(this.jPasswordField_Password.getText()))
            {
            PassW = this.jPasswordField_Password.getText();
            Confirm = true;
            }else
            {
            JOptionPane.showMessageDialog(null, "The Passwords are no the same!");
            }
        }
        if(Confirm)
        {
            LogInMenu Lim = new LogInMenu();
            DefaultTableModel modelAcc2 = (DefaultTableModel) Lim.jTable_Accounts.getModel();
            //Agregar renglon en la tabla:
            modelAcc2.addRow(new Object[]{Email,PassW});
            JOptionPane.showMessageDialog(null, "Email registered succesfully!");
        }
        }
    }//GEN-LAST:event_jPasswordField_ConfirmPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GoBack;
    private javax.swing.JButton jButton_SigIn;
    private javax.swing.JCheckBox jCheckBox_SeePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_ConfirmPassword;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_Email;
    // End of variables declaration//GEN-END:variables
}
